# Generated by Django 3.0.7 on 2020-06-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0002_auto_20200629_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellTome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('short_name', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField()),
                ('damage_per_tail', models.IntegerField()),
                ('scheme', models.CharField(choices=[('CROSS', 'Across'), ('LINE', 'Line'), ('RECTAN', 'Rectangle'), ('CF', 'Circumference')], max_length=10)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spells', to='hero_app.SpellTome')),
                ('tome', models.ManyToManyField(related_name='spells', to='hero_app.Hero')),
            ],
        ),
    ]
