# Generated by Django 3.0.7 on 2020-06-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0006_auto_20200629_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='hero',
            field=models.ManyToManyField(blank=True, related_name='spells', to='hero_app.Hero'),
        ),
    ]
