# Generated by Django 3.0.7 on 2020-06-29 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0007_auto_20200629_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='scheme',
            field=models.CharField(choices=[('CROSS', 'Across'), ('RECTAN', 'Rectangle'), ('CF', 'Circumference')], max_length=10),
        ),
        migrations.AlterField(
            model_name='spell',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
