# Generated by Django 3.0.7 on 2020-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0008_auto_20200629_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(default='Странник', max_length=24),
        ),
    ]
