# Generated by Django 3.0.7 on 2020-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0011_auto_20200702_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulthero',
            name='human_name',
            field=models.CharField(default='test', max_length=36),
            preserve_default=False,
        ),
    ]
