# Generated by Django 3.0.7 on 2020-07-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0014_auto_20200702_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='in_battle',
            field=models.BooleanField(default=False),
        ),
    ]
