# Generated by Django 3.1b1 on 2020-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0017_auto_20200707_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='army',
            field=models.JSONField(default=dict),
        ),
    ]
