# Generated by Django 3.1b1 on 2020-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0019_auto_20200707_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='default_hero',
        ),
        migrations.AddField(
            model_name='hero',
            name='default',
            field=models.CharField(choices=[('Knight', 'Рыцарь'), ('Demon', 'Демон')], default='Knight', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DefaultHero',
        ),
    ]
