# Generated by Django 3.1b1 on 2020-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0020_auto_20200708_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
