# Generated by Django 3.1b1 on 2020-07-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0022_hero_free_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='in_battle',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
