# Generated by Django 3.1b1 on 2020-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0024_auto_20200716_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='default',
            field=models.CharField(choices=[('Knight', 'Рыцарь'), ('Demon', 'Демон'), ('Elf', 'Эльф')], max_length=30),
        ),
    ]
