# Generated by Django 3.0.7 on 2020-07-03 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero_app', '0015_hero_in_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_hero', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hero_app.Hero')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
