# Generated by Django 3.0.7 on 2020-07-03 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0004_auto_20200704_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroapp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heroapp', to=settings.AUTH_USER_MODEL),
        ),
    ]
