# Generated by Django 3.1b1 on 2020-07-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='structure',
            field=models.JSONField(null=True),
        ),
    ]
