# Generated by Django 3.1b1 on 2020-07-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0002_auto_20200707_0255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Army',
        ),
    ]
