# Generated by Django 3.0.7 on 2020-07-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='placement_type',
            field=models.CharField(choices=[('FR', 'Free'), ('EQ', 'Equal'), ('MG', 'MeatGrinder')], default='EQ', max_length=2),
        ),
    ]
