# Generated by Django 3.1b1 on 2020-07-06 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0002_auto_20200704_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='combat',
            name='field_height',
        ),
        migrations.RemoveField(
            model_name='combat',
            name='field_width',
        ),
        migrations.RemoveField(
            model_name='combat',
            name='hero_placement_height',
        ),
        migrations.AddField(
            model_name='combat',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='combat_app.field'),
        ),
    ]
