# Generated by Django 3.1b1 on 2020-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0003_auto_20200707_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='obstacles',
            field=models.JSONField(null=True),
        ),
    ]
