# Generated by Django 3.1b1 on 2020-07-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0004_field_obstacles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='obstacles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
