# Generated by Django 3.1b1 on 2020-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0005_auto_20200707_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='obstacles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
