# Generated by Django 3.1b1 on 2020-07-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0006_auto_20200707_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='field',
            field=models.CharField(default='Simple', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
