# Generated by Django 3.1b1 on 2020-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0007_auto_20200708_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='combat',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
