# Generated by Django 3.1 on 2020-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0008_auto_20200721_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combat',
            name='started',
        ),
        migrations.AlterField(
            model_name='combat',
            name='status',
            field=models.CharField(choices=[(None, 'None'), ('load', 'Loading'), ('prepare', 'Prepare'), ('inbattle', 'In Battle'), ('ended', 'Ended')], default=None, max_length=8, null=True),
        ),
    ]
