# Generated by Django 3.1 on 2020-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0009_auto_20200805_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('load', 'Loading'), ('prepare', 'Prepare'), ('inbattle', 'In Battle'), ('ended', 'Ended')], default=None, max_length=8, null=True),
        ),
    ]
